require 'bundler/setup'
Bundler.require(:default)

require 'discordrb'
require 'gemini-ai'
require 'dotenv/load'
require 'json'
require 'date'

# Configuration
DISCORD_TOKEN = ENV['DISCORD_BOT_TOKEN']
GEMINI_API_KEY = ENV['GEMINI_API_KEY']
SOURCE_CHANNELS = ENV['SOURCE_CHANNEL_IDS']&.split(',') || []
TARGET_CHANNEL_ID = ENV['TARGET_CHANNEL_ID']

# Initialize Clients
def run
  begin
    main_logic
  rescue => e
    warn "CRITICAL ERROR: #{e.message}"
    warn e.backtrace.join("\n")
    exit(1)
  end
end

def main_logic
  if !DISCORD_TOKEN || !GEMINI_API_KEY || SOURCE_CHANNELS.empty? || !TARGET_CHANNEL_ID
    puts "Error: Missing environment variables."
    exit(1)
  end

  # 1. Collect Messages
  all_messages = []
  
  SOURCE_CHANNELS.each do |channel_id|
    puts "Fetching messages from #{channel_id}..."
    # Fetch last 100 messages (limit for simplicity, or implement pagination for time-based)
    # Using REST API directly avoids Gateway connection overhead
    begin
      msgs = JSON.parse(Discordrb::API::Channel.messages("Bot #{DISCORD_TOKEN}", channel_id, 50))
      
      # Filter for messages from last 24 hours
      one_day_ago = (DateTime.now - 1).to_s
      recent_msgs = msgs.select { |m| m['timestamp'] > one_day_ago }
      
      recent_msgs.each do |msg|
        author = msg['author']['username']
        content = msg['content']
        next if content.strip.empty?
        all_messages << "[#{msg['timestamp']}] #{author}: #{content}"
      end
    rescue => e
      puts "Error fetching channel #{channel_id}: #{e.message}"
    end
  end

  if all_messages.empty?
    puts "No recent messages found."
    return
  end

  puts "Collected #{all_messages.size} messages. Sending to Gemini..."

  # 2. Analyze with Gemini
  client = GeminiAi::Client.new(api_key: GEMINI_API_KEY)
  
  prompt = <<~PROMPT
    You are a helpful project manager. 
    以下はDiscordチームの雑談や殴り書きのログです。
    ここから明確な「タスク」「アイデア」「バグ報告」を抽出し、リスト化してください。
    
    1. 挨拶やただの雑談は無視してください。
    2. 創作や開発や運営に関連するアクション可能な項目を特定してください。
    3. 結果は必ず有効な **JSON配列** 形式のみで返してください。
    
    フォーマット例:
    [
      {
        "title": "ログインバグの修正",
        "description": "ログイン時に500エラーが出るとの報告あり。調査が必要。",
        "priority": "高",
        "original_context": "..."
      }
    ]

    メッセージログ:
    #{all_messages.join("\n")}
  PROMPT

  begin
    result = client.generate_content({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      model: 'gemini-2.0-flash-lite'
    })
    
    # Extract JSON from response
    raw_response = result['candidates'][0]['content']['parts'][0]['text']
    # Clean up markdown code blocks if present
    json_str = raw_response.gsub(/```json/, '').gsub(/```/, '').strip
    tasks = JSON.parse(json_str)
  rescue => e
    puts "Error calling Gemini or parsing JSON: #{e.message}"
    puts "Raw response: #{raw_response}" if raw_response
    return
  end

  if tasks.empty?
    puts "No tasks identified."
    # Optionally notify discord there were no tasks
    return
  end

  # 3. Post to Target Channel
  puts "Found #{tasks.size} tasks. Posting to Discord..."
  
  embeds = tasks.map do |task|
    {
      title: "📝 #{task['title']}",
      description: task['description'],
      color: 0x00FF00, # Green
      fields: [
        { name: "優先度", value: task['priority'] || "普通", inline: true },
        { name: "元メッセージ", value: task['original_context'] || "N/A" }
      ],
      footer: { text: "Generated by Gemini • Your Senpai Ace" }
    }
  end

  # Send summary message first
  Discordrb::API::Channel.create_message("Bot #{DISCORD_TOKEN}", TARGET_CHANNEL_ID, "アナタの先輩、エースです。\n\n昨日のメッセージを確認して **#{tasks.size}件** のタスク候補をまとめておきました。", false, nil)
  
  # Send embeds (Discord allows 10 embeds per message, but safe to send 1 by 1 or batch)
  embeds.each do |embed|
    Discordrb::API::Channel.create_message("Bot #{DISCORD_TOKEN}", TARGET_CHANNEL_ID, nil, false, embed)
    sleep 0.5 # Rate limit safety
  end
  
  puts "Done!"
end

run
